# Generated by Django 4.0.3 on 2022-04-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_hash', models.CharField(blank=True, default='', max_length=20)),
                ('tx_hash', models.CharField(blank=True, default='', max_length=100)),
                ('media_url', models.URLField()),
                ('owner', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
